name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.1]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm config set registry https://registry.npm.taobao.org
    - run: npm install
    - run: npm run build
    - run: cd dist
    - run: git init
    - run: echo 'demonskp.com.cn' > CNAME
    - run: git push -f git@github.com:demonskp/demonskp.github.io.git main
