name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install yarn -g
      - run: yarn
      - run: yarn build
      - run: git config --global user.email "demonskp@qq.com"
      - run: mkdir deploy
      - run: cd deploy
        # 部署
      - name: Deploy
        uses: actions/checkout@v2
        with:
          repository: demonskp/demonskp.github.io
          ref: main # 目标分支
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Copy build output to Repository B
        run: |
          cd ../
          ls
          cd deploy
          cp -R ../dist/* .
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m 'Deploy from repo-A'
          git push
